//
// Created by makleyston on 30/08/22.
//

#ifndef UFCITY_ERROR_LIST_H
#define UFCITY_ERROR_LIST_H

#define ERROR_JSON_PARSER 1
#define ERROR_FOG_NODE_ADDRESS 2
#define ERROR_EDGE_MODULE_NOT_INITIALIZED 3
#define ERROR_RESOURCE_ALREADY_EXIST 4
#define ERROR_SEMANTIC_ANNOTATION 5
#define ERROR_RESOURCE_NOT_FOUND 6
#define ERROR_OBSERVER_NOT_FOUND 7

#endif //UFCITY_ERROR_LIST_H
