#ifndef UFCITY_ERROR_LIST_H
#define UFCITY_ERROR_LIST_H

#define ERROR_JSON_PARSER 1
#define ERROR_FOG_NODE_ADDRESS 2
#define ERROR_EDGE_MODULE_NOT_INITIALIZED 3
#define ERROR_RESOURCE_ALREADY_EXIST 4
#define ERROR_FORMATTED_DATA 5
#define ERROR_RESOURCE_NOT_FOUND 6
#define ERROR_OBSERVER_NOT_FOUND 7
#define ERROR_SUBSCRIBE 8
#define ERROR_FOG_NODE_ADDRESS_NOT_MATCHED 9
#define ERROR_FOG_NODE_ADDRESS_EMPTY 10

#endif //UFCITY_ERROR_LIST_H
