//
// Created by makleyston on 30/08/22.
//

#ifndef UFCITY_ERROR_LIST_H
#define UFCITY_ERROR_LIST_H

#define ERROR_JSON_PARSER 1
#define ERROR_FOG_NODE_ADDRESS 2
#define ERROR_EDGE_MODULE_NOT_INITIALIZED 3
#define ERROR_RESOURCE_ALREADY_EXIST 4
#define ERROR_SEMANTIC_ANNOTATION 5
#define ERROR_RESOURCE_NOT_FOUND 6
#define ERROR_OBSERVER_NOT_FOUND 7
//#define ERROR_XXXXX 8
//#define ERROR_XXXXX 9
//#define ERROR_XXXXX 10
//#define ERROR_XXXXX 11
//#define ERROR_XXXXX 12
//#define ERROR_XXXXX 13
//#define ERROR_XXXXX 14
//#define ERROR_XXXXX 15
//#define ERROR_XXXXX 16
//#define ERROR_XXXXX 17
//#define ERROR_XXXXX 18
//#define ERROR_XXXXX 19
//#define ERROR_XXXXX20

#endif //UFCITY_ERROR_LIST_H
